# Generated by Django 3.2.17 on 2023-02-10 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_model',
            new_name='RecipeModel',
        ),
    ]
