# Generated by Django 3.2.17 on 2023-02-20 15:08

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_recipe_model_recipemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients_list',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='instructions',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
